package com.diablominer.opengl.examples.learning;

import org.lwjgl.opengl.GL33;

public enum FramebufferAttachment {

    COLOR_ATTACHMENT0 (GL33.GL_COLOR_ATTACHMENT0,  GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT1 (GL33.GL_COLOR_ATTACHMENT1,  GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT2 (GL33.GL_COLOR_ATTACHMENT2,  GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT3 (GL33.GL_COLOR_ATTACHMENT3,  GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT4 (GL33.GL_COLOR_ATTACHMENT4,  GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT5 (GL33.GL_COLOR_ATTACHMENT5,  GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT6 (GL33.GL_COLOR_ATTACHMENT6,  GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT7 (GL33.GL_COLOR_ATTACHMENT7,  GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT8 (GL33.GL_COLOR_ATTACHMENT8,  GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT9 (GL33.GL_COLOR_ATTACHMENT9,  GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT10(GL33.GL_COLOR_ATTACHMENT10, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT11(GL33.GL_COLOR_ATTACHMENT11, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT12(GL33.GL_COLOR_ATTACHMENT12, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT13(GL33.GL_COLOR_ATTACHMENT13, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT14(GL33.GL_COLOR_ATTACHMENT14, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT15(GL33.GL_COLOR_ATTACHMENT15, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT16(GL33.GL_COLOR_ATTACHMENT16, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT17(GL33.GL_COLOR_ATTACHMENT17, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT18(GL33.GL_COLOR_ATTACHMENT18, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT19(GL33.GL_COLOR_ATTACHMENT19, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT20(GL33.GL_COLOR_ATTACHMENT20, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT21(GL33.GL_COLOR_ATTACHMENT21, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT22(GL33.GL_COLOR_ATTACHMENT22, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT23(GL33.GL_COLOR_ATTACHMENT23, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT24(GL33.GL_COLOR_ATTACHMENT24, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT25(GL33.GL_COLOR_ATTACHMENT25, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT26(GL33.GL_COLOR_ATTACHMENT26, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT27(GL33.GL_COLOR_ATTACHMENT27, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT28(GL33.GL_COLOR_ATTACHMENT28, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT29(GL33.GL_COLOR_ATTACHMENT29, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT30(GL33.GL_COLOR_ATTACHMENT30, GL33.GL_COLOR_BUFFER_BIT, true),
    COLOR_ATTACHMENT31(GL33.GL_COLOR_ATTACHMENT31, GL33.GL_COLOR_BUFFER_BIT, true),
    DEPTH_ATTACHMENT  (GL33.GL_DEPTH_ATTACHMENT,   GL33.GL_DEPTH_BUFFER_BIT, false),
    STENCIL_ATTACHMENT(GL33.GL_STENCIL_ATTACHMENT, GL33.GL_STENCIL_BUFFER_BIT, false),
    DEPTH_AND_STENCIL_ATTACHMENT(GL33.GL_DEPTH_STENCIL_ATTACHMENT, GL33.GL_DEPTH_BUFFER_BIT | GL33.GL_STENCIL_BUFFER_BIT, false),;

    public final int glType;
    public final int glBitType;
    public final boolean isColorAttachment;

    FramebufferAttachment(int glType, int glBitType, boolean isColorAttachment) {
        this.glType = glType;
        this.glBitType = glBitType;
        this.isColorAttachment = isColorAttachment;
    }
}
